package com.testngclassTest;


public class SampleTestXMLandJson {

	public static void main(String[] args) {
		 String xmlString = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
	        		+"\r\n"
	        		+ "<store>\r\n"
	        		+ "  <storeName>The Grand Market</storeName>\r\n"
	        		+ "  <location>\r\n"
	        		+ "    <city>New York</city>\r\n"
	        		+ "    <state>NY</state>\r\n"
	        		+ "    <postalCode>10001</postalCode>\r\n"
	        		+ "  </location>\r\n"
	        	
	        		+ "  <employees>\r\n"
	        		+ "    <employee>\r\n"
	        		+ "      <employeeId>E001</employeeId>\r\n"
	        		+ "      <name>John Doe</name>\r\n"
	        		+ "      <position>Manager</position>\r\n"
	        		+ "      <salary>55000</salary>\r\n"
	        		+ "      <contact>\r\n"
	        		+ "        <email>john.doe@example.com</email>\r\n"
	        		+ "        <phone>123-456-7890</phone>\r\n"
	        		+ "      </contact>\r\n"
	        		+ "    </employee>\r\n"
	        		+ "    <employee>\r\n"
	        		+ "      <employeeId>E002</employeeId>\r\n"
	        		+ "      <name>Jane Smith</name>\r\n"
	        		+ "      <position>Sales Associate</position>\r\n"
	        		+ "      <salary>35000</salary>\r\n"
	        		+ "      <contact>\r\n"
	        		+ "        <email>jane.smith@example.com</email>\r\n"
	        		+ "        <phone>987-654-3210</phone>\r\n"
	        		+ "      </contact>\r\n"
	        		+ "    </employee>\r\n"
	        		+ "  </employees>\r\n"
	        		+ "  <hours>\r\n"
	        		+ "    <monday>9 AM - 7 PM</monday>\r\n"
	        		+ "    <tuesday>9 AM - 7 PM</tuesday>\r\n"
	        		+ "    <wednesday>9 AM - 7 PM</wednesday>\r\n"
	        		+ "    <thursday>9 AM - 7 PM</thursday>\r\n"
	        		+ "    <friday>9 AM - 7 PM</friday>\r\n"
	        		+ "    <saturday>10 AM - 5 PM</saturday>\r\n"
	        		+ "    <sunday>Closed</sunday>\r\n"
	        		+ "  </hours>\r\n"
	        		+ "</store>\r\n"
	        		+ ""; 

	        		;
	        String jsonString = "{\r\n"
	        		+ "  \"store\": {\r\n"
	        		+ "    \"storeName\": \"The Grand Market\",\r\n"
	        		+ "    \"location\": {\r\n"
	        		+ "      \"city\": \"New York\",\r\n"
	        		+ "      \"state\": \"hgsdhg\",\r\n"
	        		+ "      \"postalCode\": \"10001\"\r\n"
	        		+ "    },\r\n"
	        		+ "    \"products\": [\r\n"
	        		+ "      {\r\n"
	        		+ "        \"productId\": \"P001\",\r\n"
	        		+ "        \"name\": \"Laptop\",\r\n"
	        		+ "        \"category\": \"Electronics\",\r\n"
	        		+ "        \"price\": 899.99,\r\n"
	        		+ "        \"inStock\": true,\r\n"
	        		+ "        \"details\": {\r\n"
	        		+ "          \"brand\": \"Dell\",\r\n"
	        		+ "          \"processor\": \"Intel Core i7\",\r\n"
	        		+ "          \"ram\": \"16 GB\",\r\n"
	        		+ "          \"storage\": \"512 GB SSD\"\r\n"
	        		+ "        }\r\n"
	        		+ "      },\r\n"
	        		+ "      {\r\n"
	        		+ "        \"productId\": \"P002\",\r\n"
	        		+ "        \"name\": \"Smartphone\",\r\n"
	        		+ "        \"category\": \"Electronics\",\r\n"
	        		+ "        \"price\": 499.99,\r\n"
	        		+ "        \"inStock\": true,\r\n"
	        		+ "        \"details\": {\r\n"
	        		+ "          \"brand\": \"Samsung\",\r\n"
	        		+ "          \"model\": \"Galaxy S20\",\r\n"
	        		+ "          \"screenSize\": \"6.2 inches\",\r\n"
	        		+ "          \"camera\": \"64 MP\"\r\n"
	        		+ "        }\r\n"
	        		+ "      },\r\n"
	        		+ "      {\r\n"
	        		+ "        \"productId\": \"P003\",\r\n"
	        		+ "        \"name\": \"Coffee Maker\",\r\n"
	        		+ "        \"category\": \"Home Appliances\",\r\n"
	        		+ "        \"price\": 129.99,\r\n"
	        		+ "        \"inStock\": false,\r\n"
	        		+ "        \"details\": {\r\n"
	        		+ "          \"brand\": \"Breville\",\r\n"
	        		+ "          \"capacity\": \"1.5 liters\",\r\n"
	        		+ "          \"type\": \"Espresso\",\r\n"
	        		+ "          \"features\": [\r\n"
	        		+ "            \"Automatic shut-off\",\r\n"
	        		+ "            \"Removable drip tray\",\r\n"
	        		+ "            \"Stainless steel\"\r\n"
	        		+ "          ]\r\n"
	        		+ "        }\r\n"
	        		+ "      }\r\n"
	        		+ "    ],\r\n"
	        		+ "    \"employees\": [\r\n"
	        		+ "      {\r\n"
	        		+ "        \"employeeId\": \"E001\",\r\n"
	        		+ "        \"name\": \"John Doe\",\r\n"
	        		+ "        \"position\": \"Manager\",\r\n"
	        		+ "        \"salary\": 55000,\r\n"
	        		+ "        \"contact\": {\r\n"
	        		+ "          \"email\": \"john.doe@example.com\",\r\n"
	        		+ "          \"phone\": \"123-456-7890\"\r\n"
	        		+ "        }\r\n"
	        		+ "      },\r\n"
	        		+ "      {\r\n"
	        		+ "        \"employeeId\": \"E002\",\r\n"
	        		+ "        \"name\": \"Jane Smith\",\r\n"
	        		+ "        \"position\": \"Sales Associate\",\r\n"
	        		+ "        \"salary\": 35000,\r\n"
	        		+ "        \"contact\": {\r\n"
	        		+ "          \"email\": \"jane.smith@example.com\",\r\n"
	        		+ "          \"phone\": \"987-654-3210\"\r\n"
	        		+ "        }\r\n"
	        		+ "      }\r\n"
	        		+ "    ],\r\n"
	        		+ "    \"hours\": {\r\n"
	        		+ "      \"monday\": \"9 AM - 7 PM\",\r\n"
	        		+ "      \"tuesday\": \"9 AM - 7 PM\",\r\n"
	        		+ "      \"wednesday\": \"9 AM - 7 PM\",\r\n"
	        		+ "      \"thursday\": \"9 AM - 7 PM\",\r\n"
	        		+ "      \"friday\": \"9 AM - 7 PM\",\r\n"
	        		+ "      \"sunday\": \"Closed\"\r\n"
	        		+ "    }\r\n"
	        		+ "  }\r\n"
	        		+ "}\r\n"
	        		+ ""; 
	        
	        //XMLJsonCoversion.compareXmlNodesAndGenerateReport(xmlString, jsonString);
	       // XMLJsonCoversion.compareJsonNodesAndGenerateReport(xmlString, jsonString);

	}

}
