openapi: 3.0.0
info:
  title: goRest
  version: 1.0.0
servers:
  - url: https://gorest.co.in
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /public/v2/users/6930067:
    put:
      tags:
        - default
      summary: https://gorest.co.in/public/v2/users/6913950
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: sajeev
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /public/v2/users/6913950:
    get:
      tags:
        - default
      summary: https://gorest.co.in/public/v2/users/6913950
      security:
        - bearerAuth: []
      parameters:
        - name: accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
